# Copyright 2026 MCode
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

interface I2C(role)
{
    topology = "multi-point"
    mode = ["half duplex"]
    maxdistance = 10m
    maxspeed = [100kbps@10m, 400kbps@2m, 5Mbps@1m]
    voltage = [1.8V,3.3V,5V]
    pullup = 1kΩ ~ 10kΩ

    // I2C (Inter-Integrated Circuit) Standard Definition
    // Core Rule: Two-wire serial bus, supports multiple devices with unique addresses
    // I2C Level Spec: High = VCC (Logic 1), Low = GND (Logic 0) - open drain with pullups
    // Device Definition: Master = Initiates communication, Slave = Responds to master
    // Addressing: 7-bit or 10-bit device addresses

    // @drive(od): the I2C bus is open-drain with external pullups — every node
    // releases the line by driving high. A push-pull driver states
    // `@drive(pp)` on its own adoption row, which overrides this default.
    pins = [
        1 = SCL @drive(od), "Serial Clock"  // Clock signal, generated by master
        2 = SDA @drive(od), "Serial Data"  // Bi-directional data signal
    ]
    
    role Master {  // I2C Master - Initiates communication
        name = "I2C Master"
        pins = [
            out 1 = SCL @drive(od), "Serial Clock"  // The master sources the clock
            io 2 = SDA @drive(od), "Serial Data"    // Either side drives the data line
        ]
        peer = Slave
    }
    role Slave {  // I2C Slave - Responds to master
        name = "I2C Slave"
        pins = [
            in 1 = SCL @drive(od), "Serial Clock"  // Clock stretching holds SCL low; the master stays the clock source
            io 2 = SDA @drive(od), "Serial Data"   // Either side drives the data line
        ]
        peer = Master
    }
}

// ---------------------------------------------------------------------------------------------
// I2C.SMBUS — System Management Bus (I2C variant)
// ---------------------------------------------------------------------------------------------

interface I2C.SMBUS(role)
{
    topology = "multi-point"
    mode = ["half duplex"]
    maxdistance = 1m  // Typically on-board / backplane
    maxspeed = [10kbps@1m, 100kbps@0.5m]  // 10 kHz minimum, 100 kHz max
    voltage = [1.8V, 3.3V, 5V]
    pullup = 1kΩ ~ 10kΩ

    // SMBus (System Management Bus) — SBS Implementers Forum specification
    // Core Rule: I2C variant with fixed voltage/timing, timeout, and protocol constraints
    // Applications: Smart battery, thermal monitoring, power management
    // Key differences from I2C: minimum 10 kHz clock, timeout, packet error checking

    // @drive(od): like I2C, the bus is open-drain with external pullups. A
    // push-pull driver states `@drive(pp)` on its own adoption row, which
    // overrides this default.
    pins = [
        1 = SCL @drive(od), "Serial Clock"  // Clock signal
        2 = SDA @drive(od), "Serial Data"  // Bidirectional data
        3 = ALERT @drive(od), "SMBus Alert"  // Optional interrupt / alert line
    ]

    role Host {  // SMBus Host - Initiates communication
        name = "SMBus Host"
        pins = [
            out 1 = SCL @drive(od), "Serial Clock"  // The host sources the clock
            io 2 = SDA @drive(od), "Serial Data"    // Either side drives the data line
            in 3 = ALERT @drive(od), "SMBus Alert"  // Slaves pull ALERT low to request attention
        ]
        peer = Slave
    }
    role Slave {  // SMBus Slave - Responds to host
        name = "SMBus Slave"
        pins = [
            in 1 = SCL @drive(od), "Serial Clock"  // Clock stretching holds SCL low; the host stays the clock source
            io 2 = SDA @drive(od), "Serial Data"   // Either side drives the data line
            out 3 = ALERT @drive(od), "SMBus Alert"  // The slave asserts ALERT
        ]
        peer = Host
    }
}
