# Copyright (c) 2026 MCode. Built with MCode Bench(TM).
# Licensed under the Apache License, Version 2.0.

// I2C - Inter-Integrated Circuit Bus Interface Standard Definition
// Core Rule: Two-wire multi-point bus, open-drain with external pullups
//            — every node releases the line by driving high, so high =
//            VCC only after the release; a push-pull driver states
//            @drive(pp) on its own adoption row. Devices are addressed
//            by 7-bit or 10-bit addresses; slaves may stretch the clock
//            while the master stays the clock source.
// Device Definition: MASTER = initiates every transfer and sources SCL,
//                    SLAVE = responds when addressed (may stretch the
//                    clock).

interface I2C(role)
{
    topology = "multi-point"
    mode = ["half duplex"]
    maxdistance = 10m
    maxspeed = [100kbps@10m, 400kbps@2m, 5Mbps@1m]
    voltage = [1.8V,3.3V,5V]
    pullup = 1kΩ ~ 10kΩ

    // @drive(od): the I2C bus is open-drain with external pullups — every
    // node releases the line by driving high. A push-pull driver states
    // `@drive(pp)` on its own adoption row, which overrides this default.
    pins = [
        1 = SCL @drive(od) @class(digital), "Serial Clock"  // Clock signal, generated by master
        2 = SDA @drive(od) @class(digital), "Serial Data"  // Bi-directional data signal
    ]
    
    role MASTER {  // I2C Master - Initiates communication
        name = "I2C Master"
        pins = [
            out 1 = SCL @drive(od) @class(digital), "Serial Clock"  // The master sources the clock
            io 2 = SDA @drive(od) @class(digital), "Serial Data"    // Either side drives the data line
        ]
        peer = SLAVE
    }
    role SLAVE {  // I2C Slave - Responds to master
        name = "I2C Slave"
        pins = [
            in 1 = SCL @drive(od) @class(digital), "Serial Clock"  // Clock stretching holds SCL low; the master stays the clock source
            io 2 = SDA @drive(od) @class(digital), "Serial Data"   // Either side drives the data line
        ]
        peer = MASTER
    }
}

// I2C.SMBUS - System Management Bus Interface (I2C variant) Standard Definition
// Core Rule: I2C variant with fixed voltage/timing discipline: minimum
//            10kHz clock, timeout, and packet error checking. Open-drain
//            with external pullups, plus an optional ALERT line that
//            slaves pull low to request attention.
// Device Definition: HOST = initiates communication,
//                    SLAVE = responds to host (asserts ALERT).

interface I2C.SMBUS(role)
{
    topology = "multi-point"
    mode = ["half duplex"]
    maxdistance = 1m  // Typically on-board / backplane
    maxspeed = [10kbps@1m, 100kbps@0.5m]  // 10 kHz minimum, 100 kHz max
    voltage = [1.8V, 3.3V, 5V]
    pullup = 1kΩ ~ 10kΩ

    // @drive(od): like I2C, the bus is open-drain with external pullups. A
    // push-pull driver states `@drive(pp)` on its own adoption row, which
    // overrides this default.
    pins = [
        1 = SCL @drive(od) @class(digital), "Serial Clock"  // Clock signal
        2 = SDA @drive(od) @class(digital), "Serial Data"  // Bidirectional data
        3 = ALERT @drive(od) @class(digital), "SMBus Alert"  // Optional interrupt / alert line
    ]

    role HOST {  // SMBus Host - Initiates communication
        name = "SMBus Host"
        pins = [
            out 1 = SCL @drive(od) @class(digital), "Serial Clock"  // The host sources the clock
            io 2 = SDA @drive(od) @class(digital), "Serial Data"    // Either side drives the data line
            in 3 = ALERT @drive(od) @class(digital), "SMBus Alert"  // Slaves pull ALERT low to request attention
        ]
        peer = SLAVE
    }
    role SLAVE {  // SMBus Slave - Responds to host
        name = "SMBus Slave"
        pins = [
            in 1 = SCL @drive(od) @class(digital), "Serial Clock"  // Clock stretching holds SCL low; the host stays the clock source
            io 2 = SDA @drive(od) @class(digital), "Serial Data"   // Either side drives the data line
            out 3 = ALERT @drive(od) @class(digital), "SMBus Alert"  // The slave asserts ALERT
        ]
        peer = HOST
    }
}
