# Copyright (c) 2026 MCode. Built with MCode Bench(TM).
# Licensed under the Apache License, Version 2.0.

// SDIO - Secure Digital I/O Card Interface (4-bit) Standard Definition
// Core Rule: Six wires: a host-sourced clock, one bidirectional
//            command/response line (CMD), and four bidirectional data
//            lines (DAT3 doubles as card select in the SPI mode).
//            3.3V default, 1.8V in the UHS modes.
// Device Definition: HOST = MCU/SoC SD host controller,
//                    CARD = SD memory or SDIO peripheral card.

interface SDIO(role)
{
    topology = "point to point"
    mode = ["half duplex", "full duplex"]  // 1-bit / 4-bit modes
    maxdistance = 0.1m  // PCB trace only
    maxspeed = [25MHz@0.1m, 50MHz@0.1m, 100MHz@0.1m, 208MHz@0.1m]  // Default / High / UHS-I / UHS-II
    voltage = [1.8V, 3.3V]  // 3.3V default, 1.8V for UHS-I

    pins = [
        1 = CLK @class(digital), "Clock"             // Clock signal, generated by host
        2 = CMD @class(digital), "Command"           // Bidirectional command/response line
        3 = DAT0 @class(digital), "Data 0"           // Bidirectional data line 0
        4 = DAT1 @class(digital), "Data 1"           // Bidirectional data line 1
        5 = DAT2 @class(digital), "Data 2"           // Bidirectional data line 2
        6 = DAT3, "Data 3"           // Bidirectional data line 3 (also CS in SPI mode)
    ]

    role HOST {  // SDIO Host (MCU/SoC)
        name = "SDIO Host"
        pins = [
            out 1 = CLK @class(digital), "Clock"     // The host sources the clock
            io 2 = CMD @class(digital), "Command"    // Command out, response in — either side drives
            io 3 = DAT0 @class(digital), "Data 0"    // Bidirectional data line 0
            io 4 = DAT1 @class(digital), "Data 1"    // Bidirectional data line 1
            io 5 = DAT2 @class(digital), "Data 2"    // Bidirectional data line 2
            io 6 = DAT3, "Data 3"    // Bidirectional data line 3 (also CS in SPI mode)
        ]
        peer = CARD
    }
    role CARD {  // SDIO Card (SD card / SDIO peripheral)
        name = "SDIO Card"
        pins = [
            in 1 = CLK @class(digital), "Clock"      // The clock is an input on the card side
            io 2 = CMD @class(digital), "Command"    // Command out, response in — either side drives
            io 3 = DAT0 @class(digital), "Data 0"    // Bidirectional data line 0
            io 4 = DAT1 @class(digital), "Data 1"    // Bidirectional data line 1
            io 5 = DAT2 @class(digital), "Data 2"    // Bidirectional data line 2
            io 6 = DAT3, "Data 3"    // Bidirectional data line 3 (also CS in SPI mode)
        ]
        peer = HOST
    }
}

// SDIO.1 - Secure Digital I/O Card Interface (1-bit bus) Standard Definition
// Core Rule: The 1-bit SD mode — clock, CMD, and a single data line, the
//            fallback when fewer data lines are available.
// Device Definition: HOST = MCU/SoC SD host controller,
//                    CARD = SD memory or SDIO peripheral card.

interface SDIO.1(role)
{
    topology = "point to point"
    mode = ["half duplex"]
    maxdistance = 0.1m
    maxspeed = [25MHz@0.1m, 50MHz@0.1m]
    voltage = [1.8V, 3.3V]

    // 1-bit SD mode — fallback when fewer data lines are available

    pins = [
        1 = CLK @class(digital), "Clock"             // Clock signal
        2 = CMD @class(digital), "Command"           // Bidirectional command/response line
        3 = DAT0 @class(digital), "Data 0"           // Bidirectional data line
    ]

    role HOST {
        name = "SDIO Host"
        pins = [
            out 1 = CLK @class(digital), "Clock"   // The host sources the clock
            io 2 = CMD @class(digital), "Command"  // Command out, response in — either side drives
            io 3 = DAT0 @class(digital), "Data 0"  // Bidirectional data line
        ]
        peer = CARD
    }
    role CARD {
        name = "SDIO Card"
        pins = [
            in 1 = CLK @class(digital), "Clock"    // The clock is an input on the card side
            io 2 = CMD @class(digital), "Command"  // Command out, response in — either side drives
            io 3 = DAT0 @class(digital), "Data 0"  // Bidirectional data line
        ]
        peer = HOST
    }
}
