# Copyright 2026 MCode
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

// ---------------------------------------------------------------------------------------------
// SPI — Serial Peripheral Interface (4-wire)
// ---------------------------------------------------------------------------------------------

interface SPI(role)
{
    topology = "point to point"
    mode = ["full duplex"]
    maxdistance = 10m
    maxspeed = [10Mbps@10m, 25Mbps@2m, 50Mbps@1m]
    voltage = [1.8V,3.3V,5V]

    // SPI (Serial Peripheral Interface) Standard Definition
    // Core Rule: Four-wire synchronous serial bus, high speed
    // SPI Level Spec: High = VCC (Logic 1), Low = GND (Logic 0)
    // Device Definition: MASTER = Controls the bus, SLAVE = Responds to master
    // Modes: Supports 4 different clock polarity and phase combinations (Mode 0-3)

    // Role tables declare each role's wiring order: ordinal k on the two sides is
    // the SAME wire, so the data pair crosses by position (MOSI <-> SI, MISO <-> SO).
    // Member names are each side's local view, never a matching criterion.
    // Canonical pin order (project ruling, scoped to this 4-wire table): the
    // documentation order SCLK, MOSI, MISO, _CS — clock first, data pair, CS last.
    // SPI.3 and SPI.QUAD keep _CS first: they have no data pair to cross, and
    // QUAD mirrors the JEDEC flash layout; the ruling above does not extend to them.

    // Role-less conductor view: 4 anonymous lanes, ordinal = wire identity
    // (conductor-view-design.md R-CV1). Mediated devices (buffers, level
    // shifters) and module ports bind role-less and take their shape from
    // this table; the role tables below carry the named views.
    pins = [
        1 = _ @class(digital) // SCLK
        2 = _ @class(digital) // MOSI <-> SI
        3 = _ @class(digital) // MISO <-> SO
        4 = _ @class(digital) // _CS
    ]

    role MASTER {  // SPI Master - Controls the bus
        name = "SPI Master"
        pins = [
            out 1 = SCLK @class(digital), "Serial Clock"         // Clock, driven by master
            out 2 = MOSI @class(digital), "Master Out Slave In"  // Data from master to slave (my output)
            in 3 = MISO @class(digital), "Master In Slave Out"  // Data from slave to master (my input)
            out 4 = _CS @class(digital), "Chip Select"            // Slave select
        ]
        peer = SLAVE
    }
    role SLAVE {  // SPI Slave - Responds to master
        name = "SPI Slave"
        pins = [
            in 1 = SCLK @class(digital), "Serial Clock"          // Clock, from master
            in 2 = SI @class(digital), "Slave In (from Master)"  // Data from master to slave (my input)
            out 3 = SO @class(digital), "Slave Out (to Master)"   // Data from slave to master (my output)
            in 4 = _CS @class(digital), "Chip Select"             // Slave select
        ]
        peer = MASTER
    }
}

// ---------------------------------------------------------------------------------------------
// SPI.3 — 3-Wire SPI (half-duplex, single bidirectional data line)
// ---------------------------------------------------------------------------------------------

interface SPI.3(role)
{
    topology = "point to point"
    mode = ["half duplex"]  // Half duplex since using single data line
    maxdistance = 10m
    maxspeed = [10Mbps@10m, 25Mbps@2m, 50Mbps@1m]
    voltage = [1.8V,3.3V,5V]

    // 3-Wire SPI Standard Definition
    // Core Rule: Three-wire synchronous serial bus, high speed
    // SPI Level Spec: High = VCC (Logic 1), Low = GND (Logic 0)
    // Device Definition: MASTER = Controls the bus, SLAVE = Responds to master
    // Modes: Supports 4 different clock polarity and phase combinations (Mode 0-3)
    // Note: Uses single bidirectional data line instead of separate MISO/MOSI

    pins = [
        1 = _CS @class(digital), "Chip Select"      // Slave select
        2 = SCLK @class(digital), "Serial Clock"   // Clock signal, generated by master
        3 = SDA @class(digital), "Serial Data"     // Bidirectional data line
    ]

    role MASTER {  // SPI Master - Controls the bus
        name = "SPI Master"
        pins = [
            out 1 = _CS @class(digital), "Chip Select"    // Slave select
            out 2 = SCLK @class(digital), "Serial Clock" // Clock, driven by master
            io 3 = SDA @class(digital), "Serial Data"    // Single bidirectional data line
        ]
        peer = SLAVE
    }
    role SLAVE {  // SPI Slave - Responds to master
        name = "SPI Slave"
        pins = [
            in 1 = _CS @class(digital), "Chip Select"   // Slave select
            in 2 = SCLK @class(digital), "Serial Clock" // Clock, from master
            io 3 = SDA @class(digital), "Serial Data"   // Single bidirectional data line
        ]
        peer = MASTER
    }
}

// ---------------------------------------------------------------------------------------------
// SPI.QUAD — Quad SPI (6-wire, 4 bidirectional data lines)
// ---------------------------------------------------------------------------------------------

interface SPI.QUAD(role)
{
    topology = "point to point"
    mode = ["half duplex", "full duplex"]  // Dual/Quad modes
    maxdistance = 0.1m  // PCB trace only
    maxspeed = [133MHz@0.1m]  // Typical NOR flash interface speed
    voltage = [1.8V, 3.3V]

    // QSPI (Quad SPI) — JEDEC JESD216 (SFDP) de facto standard
    // Core Rule: 6-wire SPI variant with 4 bidirectional data lines
    // Used primarily for NOR flash memory interfaces
    // Modes: Single (1-bit), Dual (2-bit), Quad (4-bit)

    pins = [
        1 = _CS @class(digital), "Chip Select"         // Slave select
        2 = SCLK @class(digital), "Serial Clock"      // Clock signal, generated by master
        3 = IO0 @class(digital), "I/O 0"              // Bidirectional data line 0 (MOSI in single mode)
        4 = IO1 @class(digital), "I/O 1"              // Bidirectional data line 1 (MISO in single mode)
        5 = IO2, "I/O 2"              // Bidirectional data line 2 (WP# in single mode)
        6 = IO3, "I/O 3"              // Bidirectional data line 3 (HOLD# in single mode)
    ]

    role MASTER {  // QSPI Master (typically MCU/SoC)
        name = "QSPI Master"
        pins = [
            out 1 = _CS @class(digital), "Chip Select"    // Slave select
            out 2 = SCLK @class(digital), "Serial Clock" // Clock, driven by master
            io 3 = IO0 @class(digital), "I/O 0"          // Bidirectional data line 0
            io 4 = IO1 @class(digital), "I/O 1"          // Bidirectional data line 1
            io 5 = IO2, "I/O 2"          // Bidirectional data line 2
            io 6 = IO3, "I/O 3"          // Bidirectional data line 3
        ]
        peer = SLAVE
    }
    role SLAVE {  // QSPI Slave (typically NOR Flash)
        name = "QSPI Slave"
        pins = [
            in 1 = _CS @class(digital), "Chip Select"   // Slave select
            in 2 = SCLK @class(digital), "Serial Clock" // Clock, from master
            io 3 = IO0 @class(digital), "I/O 0"        // Bidirectional data line 0
            io 4 = IO1 @class(digital), "I/O 1"        // Bidirectional data line 1
            io 5 = IO2, "I/O 2"        // Bidirectional data line 2
            io 6 = IO3, "I/O 3"        // Bidirectional data line 3
        ]
        peer = MASTER
    }
}

// ---------------------------------------------------------------------------------------------
// SPI.WO — Write-Only SPI (3-wire, unidirectional data line)
// ---------------------------------------------------------------------------------------------

interface SPI.WO(role)
{
    topology = "point to point"
    mode = ["write-only"]  // The master writes; the slave has no data output
    maxdistance = 10m
    maxspeed = [10Mbps@10m, 25Mbps@2m, 50Mbps@1m]
    voltage = [1.8V,3.3V,5V]

    // Write-Only SPI Standard Definition
    // Core Rule: Three-wire synchronous serial link, data flows one way only
    // Device Definition: MASTER = Controls the link, SLAVE = Responds to master
    // Shape witness: MCP4921-family DACs (DS22248A: CS/SCK/SDI, no SO pin).
    // A write-only slave cannot conform to the full SPI table (wire 3 SO has
    // no pin to carry it) and SPI.3's SDA is bidirectional -- neither face
    // types a slave whose data pin is input-only.
    // Note: keeps CS first like SPI.3 (no data pair to cross).

    // Role-less conductor view (conductor-view-design.md R-CV1): 3 anonymous
    // lanes, ordinal = wire identity. Wire 3 crosses SO <-> SI, so the view
    // must not assert either side's name; wires 1-2 keep the anonymous form
    // for uniformity with the SPI 4-wire view.
    pins = [
        1 = _ @class(digital) // CS
        2 = _ @class(digital) // SCLK
        3 = _ @class(digital) // SO <-> SI
    ]

    role MASTER {  // SPI.WO Master - Controls the link
        name = "SPI.WO Master"
        pins = [
            out 1 = _CS @class(digital), "Chip Select"    // Slave select
            out 2 = SCLK @class(digital), "Serial Clock" // Clock, driven by master
            out 3 = SO @class(digital), "Serial Data Out" // Data from master to slave (my output)
        ]
        peer = SLAVE
    }
    role SLAVE {  // SPI.WO Slave - Receives configuration / data words
        name = "SPI.WO Slave"
        pins = [
            in 1 = _CS @class(digital), "Chip Select"   // Slave select
            in 2 = SCLK @class(digital), "Serial Clock" // Clock, from master
            in 3 = SI @class(digital), "Slave In (from Master)" // Data from master to slave (my input)
        ]
        peer = MASTER
    }
}
